{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "bfb29777-67bb-4aed-822b-da29c9de23d4",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (116163550.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[1], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    services:\u001b[0m\n\u001b[1;37m             ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "services:\n",
    "  - type: web\n",
    "    name: flask-api\n",
    "    env: python\n",
    "    plan: free\n",
    "    buildCommand: \"pip install -r requirements.txt\"\n",
    "    startCommand: \"gunicorn -b 0.0.0.0:5000 app:app\"\n",
    "    envVars:\n",
    "      - key: PORT\n",
    "        value: 5000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "40e11717-b90b-42f6-8ff8-5e67f3596624",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
